//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AP_Pokemon.Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int PokemonID { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> Attack { get; set; }
        public string Type { get; set; }
        public string Species { get; set; }
    }
}
